#!/usr/bin/env python2.7
# Scan a timesheet file for datetime entries of the type: [2017-03-13 11:45AM]
# Calculate the time between entries and use the first sentence of the first line as an identifier.
# Coalesce and total the hours from all identifiers which do not start with '-' and print them at the end.

# TODO: "Project" support based on ":" character?
# TODO: JIRA integration?
from __future__ import print_function
import os
import sys
import time
from datetime import datetime, timedelta

def roundTime(dt=None, roundTo=60):
	"""Round a datetime object to any time laps in seconds
	dt : datetime.datetime object, default now.
	roundTo : Closest number of seconds to round to, default 1 minute.
	Author: Thierry Husson 2012 - Use it as you want but don't blame me.
	"""
	if dt == None : dt = datetime.now()
	seconds = (dt - dt.min).seconds
	rounding = (seconds+roundTo/2) // roundTo * roundTo
	return dt + timedelta(0,rounding-seconds,-dt.microsecond)

def report(timesheet_file):
	last_timestamp = None
	id_line = False
	id = ""
	ids = {}
	for line in timesheet_file:
		try:
			# *Not* ISO 8601 for the time portion, but I hate 24h time for readability
			timestamp = datetime.strptime(line, '[%Y-%m-%d %I:%M%p]\n')
			id_line = True
			if last_timestamp is not None:
				hours = (timestamp - last_timestamp).total_seconds()/60/60
				print("\t%.2fh" % hours)
				ids[id] += hours
			last_timestamp = timestamp
			print(line),
		except ValueError:
			print(line),
			if id_line:
				id = line.strip().split(".")[0]
				id_line = False
				if not id in ids:
					ids[id] = 0.0

	print("\n")

	total_hours = 0
	for id, hours in sorted(ids.iteritems(), key=lambda (k,v): (v,k)):
		if id[:1] is not '-':
			total_hours += hours
			print("%.2fh: %s" % (hours, id))

	print("\n%.2fh: Total" % total_hours)

time_dir=os.path.expanduser(os.getenv('TIMESHEET_TIMEDIR', os.getcwd()))
today_timesheet_path = time.strftime(time_dir + "/%Y-%m-%d")

editor=os.getenv('TIMESHEET_EDITOR', 'vim')

import argparse
parser = argparse.ArgumentParser(
	description='Generate reports for timesheet files. With no arguments, create new timesheet in $TIMESHEET_TIMEDIR for the current date with $TIMESHEET_EDITOR.',
	epilog='$TIMESHEET_TIMEDIR defaults for current directory when undefined. $TIMESHEET_EDITOR defaults to vim when undefined.')
parser.add_argument(
	"-r",
	help="Generate a time report for TIMESHEET. TIMESHEET defaults to current date in $TIMESHEET_TIMEDIR",
	nargs='?',
	metavar='TIMESHEET',
	type=argparse.FileType('r'),
	const=today_timesheet_path)
parser.add_argument(
	"-d",
	help="Generate reports for the last DAYS days, if they exist. Starts from TIMESHEET file if specified, uses current date if not. Defaults to 10 DAYS.",
	nargs='?',
	metavar='DAYS',
	type=int,
	const=10)
parser.add_argument(
	"-s",
	help="Generate a current timestamp rounded to the nearest 15 minutes.",
	action="store_true")
args = parser.parse_args()

if args.r is not None:
	file_path = os.path.realpath(args.r.name)
else:
	file_path = today_timesheet_path

if args.d is not None:
	file_date = datetime.strptime(os.path.basename(file_path), '%Y-%m-%d')
	file_date = file_date - timedelta(days=args.d-1)
	while args.d > 0:
		file_path = os.path.dirname(file_path) + "/" + file_date.strftime('%Y-%m-%d')
		if os.path.isfile(file_path):
			print(file_date.strftime('Report for %a %Y-%m-%d:'))
			report(open(file_path))
			print("\n")
		file_date = file_date + timedelta(days=1)
		args.d -= 1
elif args.r is not None:
	report(args.r)
elif args.s:
	print("[%s]" % (roundTime(roundTo=60*15).strftime("%Y-%m-%d %I:%M%p")),end = '')
else:
	os.system(editor + " " + today_timesheet_path)